<a href="https://colab.research.google.com/github/PedroHBachiega/am-t4-s1a2026/blob/main/am_t4_s1a2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução de Python

In [ ]:
a=2
b=3
print('A soma é :', a+b)

A soma é : 5

## Segunda Camada

In [ ]:
c=4
d=5
print('A multiplicação é:', c*d)

A multiplicação é: 20

## Bibliotecas e Funções de Python

In [ ]:
import math

def equacao2grau(a,b,c):
  delta = b**2 - 4*a*c

  if (delta < 0):
    return 'Número sem Raíz', delta

  x1 = (-b + math.sqrt(delta)) / (2*a)
  x2 = (-b - math.sqrt(delta)) / (2*a)

  return x1, x2

## Testes de Função Matemática

In [ ]:
eq = equacao2grau(1, -3, 2)
print(eq)

(2.0, 1.0)

In [ ]:
import random

for i in range(5):
  a = random.randint(-5, 5)
  b = random.randint(-10, 10)
  c = random.randint(-10, 10)

  eq += equacao2grau(a, b, c)

In [ ]:
for i in range(12):
  if(i % 2 == 0):
    if (eq[i] != 'Número sem raiz'):
      print('X1: [', eq[i],']')
  else:
    if (eq[i] != 'Número sem raiz'):
      print('X2: [', eq[i],']\n')

X1: [ 4.212214450449026 ]
X2: [ -0.712214450449026 ]

X1: [ 1.0 ]
X2: [ 2.0 ]

X1: [ 0.5857864376269049 ]
X2: [ 3.414213562373095 ]

X1: [ 0.6 ]
X2: [ 0.0 ]

X1: [ -1.2947270864500684 ]
X2: [ 1.5447270864500684 ]

X1: [ -0.5225881209433405 ]
X2: [ 3.1892547876100075 ]

# Trabalhando com Dados Externos

## Bibliotecas de uso da pipeline

In [1]:
!pip -q install plotly
!pip -q install yellowbrick

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
base_credit = pd.read_csv('/content/drive/MyDrive/amt4/credit_data.csv')

In [5]:
base_credit

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [6]:
base_credit [base_credit['income'] > 69995.0]

     clientid        income        age         loan  default
422       423  69995.685578  52.719673  2084.370861        0

In [7]:
base_credit [base_credit['loan'] <= 1.377630]

     clientid        income        age     loan  default
865       866  28072.604355  54.142548  1.37763        0

# Análises de Anomalias Exploratórias

## Análise de anomalia Idade Negativa

In [9]:
base_credit.loc[base_credit['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0